/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DTO.Usuario;

import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import Persistencia.UsuarioDao;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

import Persistencia.UsuarioDao;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author TheusGG
 */
public class CadastroUsuario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroUsuario
     */
    public CadastroUsuario() {
        initComponents();

        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSenha = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        lblCPF1 = new javax.swing.JLabel();
        txtCPF = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtTelefone = new javax.swing.JTextField();
        txtLogin = new javax.swing.JTextField();
        txtSenha = new javax.swing.JPasswordField();
        cmbCargo = new javax.swing.JComboBox<>();
        btnLimpar = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnAlterar = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        lblPainel = new javax.swing.JLabel();
        lblfundo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Usuário");
        setIconImage(new ImageIcon(getClass().getResource("/Imagem/iconloja.png")).getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblSenha.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblSenha.setForeground(new java.awt.Color(255, 255, 255));
        lblSenha.setText("Senha:");
        getContentPane().add(lblSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 70, -1));

        lblTelefone.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTelefone.setForeground(new java.awt.Color(255, 255, 255));
        lblTelefone.setText("Tel:");
        getContentPane().add(lblTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 80, -1));

        lblCPF.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(255, 255, 255));
        lblCPF.setText("Cargo:");
        getContentPane().add(lblCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, 60, -1));

        lblEmail.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("E-mail:");
        getContentPane().add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 20));

        lblLogin.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("Login:");
        getContentPane().add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 60, -1));

        lblNome1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblNome1.setForeground(new java.awt.Color(255, 255, 255));
        lblNome1.setText("Nome:");
        getContentPane().add(lblNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, -1));

        lblCPF1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblCPF1.setForeground(new java.awt.Color(255, 255, 255));
        lblCPF1.setText("CPF:");
        getContentPane().add(lblCPF1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 50, -1));

        txtCPF.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtCPF.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtCPF, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 100, 140, -1));

        txtNome.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtNome.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 240, -1));

        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 240, -1));

        txtTelefone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtTelefone.setForeground(new java.awt.Color(51, 51, 51));
        getContentPane().add(txtTelefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 130, 140, -1));

        txtLogin.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 140, -1));

        txtSenha.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        txtSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaActionPerformed(evt);
            }
        });
        getContentPane().add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 140, -1));

        cmbCargo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbCargo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Supervisor", "Atendente" }));
        cmbCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCargoActionPerformed(evt);
            }
        });
        getContentPane().add(cmbCargo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 100, -1, -1));

        btnLimpar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnLimpar.setText("Limpar");
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        getContentPane().add(btnLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 100, 30));

        btnSalvar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, -1, 30));

        btnAlterar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnAlterar.setText("Alterar");
        btnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAlterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, -1, 30));

        btnExcluir.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        getContentPane().add(btnExcluir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 100, 30));

        btnConsultar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 120, 30));

        lblPainel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblPainel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/Agenda-PainelFundo.png"))); // NOI18N
        lblPainel.setText("jLabel1");
        getContentPane().add(lblPainel, new org.netbeans.lib.awtextra.AbsoluteConstraints(-50, -20, 460, 320));

        lblfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/cadastro_icon.png"))); // NOI18N
        getContentPane().add(lblfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 400, 310));

        jSair.setText("Sair");
        jSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jSairMouseClicked(evt);
            }
        });
        jSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSairActionPerformed(evt);
            }
        });
        jMenuBar1.add(jSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(416, 349));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        limpar();
    }

    private void limpar() {

        txtCPF.setText("");
        txtTelefone.setText("");
        txtNome.setText("");
        txtEmail.setText("");
        txtLogin.setText("");
        txtSenha.setText("");


    }//GEN-LAST:event_btnLimparActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Persistencia.UsuarioDao usuarioDao = new UsuarioDao();
        DTO.Usuario usuario = new DTO.Usuario();
        usuario.Nome = txtNome.getText();
        usuario.Login = txtLogin.getText();
        usuario.Senha = txtSenha.getText();
        usuario.CPF = txtCPF.getText();
        usuario.Telefone = txtTelefone.getText();
        usuario.Email = txtEmail.getText();
        usuario.Cargo = cmbCargo.getSelectedItem().toString();
        int result = usuarioDao.Salvar(usuario);
        if (result == 1) { // se conectou {

            JOptionPane.showMessageDialog(null, "Usuario " + txtNome.getText() + " cadastrado com sucesso.");

            

        } else {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao cadastrar usuário");
        }


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        Persistencia.UsuarioDao usuarioDao = new UsuarioDao();
        usuarioDao.Deletar(txtCPF.getText());
        limpar();
        btnExcluir.setEnabled(false);
        btnAlterar.setEnabled(false);


    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

        UsuarioDao usuarioDao = new UsuarioDao();
        Usuario usuario = usuarioDao.ConsultarPorUser(txtCPF.getText());

        txtSenha.setText(usuario.Senha);
        txtNome.setText(usuario.Nome);
        txtLogin.setText(usuario.Login);
        txtEmail.setText(usuario.Email);
        txtTelefone.setText(usuario.Telefone);
        btnExcluir.setEnabled(true);
        btnAlterar.setEnabled(true);
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarActionPerformed

        try {
            Connection con;
            PreparedStatement st;

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lojinha", "root", "46813252");

            st = con.prepareStatement("UPDATE usuario SET Nome=?, Login=?, Senha=?, Telefone=?, Email=? WHERE CPF=?");
            st.setString(1, txtNome.getText());
            st.setString(2, txtLogin.getText());
            st.setString(3, txtSenha.getText());
            st.setString(4, txtTelefone.getText());
            st.setString(5, txtEmail.getText());
            st.setString(6, txtCPF.getText());
            st.executeUpdate();
            
              JOptionPane.showMessageDialog(null, "Dados alterados com sucesso");
            limpar();
            btnExcluir.setEnabled(false);
            btnAlterar.setEnabled(false);
            txtCPF.setEditable(true);

        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro na alteração dos dados " + ex.getMessage());
        }


    }//GEN-LAST:event_btnAlterarActionPerformed

    private void jSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSairActionPerformed
 
       
    }//GEN-LAST:event_jSairActionPerformed

    private void jSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSairMouseClicked
        this.dispose();
       
      Menu b;
      b = new Menu();
      b.setVisible(true);
      
    }//GEN-LAST:event_jSairMouseClicked

    private void cmbCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCargoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroUsuario.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cmbCargo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jSair;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPF1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel lblPainel;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblfundo;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables

   

}
