/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
/**
 *
 * @author TheusGG
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Progresso = new javax.swing.JProgressBar();
        lblCarregando = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("INICIO");
        setIconImage(new ImageIcon(getClass().getResource("/Imagem/iconloja.png")).getImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Progresso.setBackground(new java.awt.Color(153, 153, 153));
        getContentPane().add(Progresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 320, 230, -1));
        getContentPane().add(lblCarregando, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 340, 40, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/oie_303849WBrQp7NN.gif"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 330, -1, 40));

        lblFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/CAPA (2).jpg"))); // NOI18N
        getContentPane().add(lblFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-70, -60, -1, -1));

        setSize(new java.awt.Dimension(507, 419));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        Inicio carregamento;
          carregamento = new Inicio();
          
          //TelaLogin a;
          //a = new TelaLogin();

          carregamento.setVisible(true);

        try {
            
            for (int i = 0; i <= 100; i += 2) {

                Thread.sleep(70);
                carregamento.Progresso.setValue(i);
                carregamento.lblCarregando.setText(Integer.toString(i) + "%");

            }
           
            carregamento.dispose();
            
            Login tl = new Login();
            tl.setVisible(true);
            
            } catch (InterruptedException ex) {
            JOptionPane.showMessageDialog(null, "Erro");
        }
            
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar Progresso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCarregando;
    private javax.swing.JLabel lblFundo;
    // End of variables declaration//GEN-END:variables
}
