/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import DTO.Tabela;
import DTO.Produto;

import DTO.Produto;
import DTO.Usuario;
import Persistencia.UsuarioDao;

import Persistencia.ProdutoDao;
import Persistencia.VendaDao;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

import javax.swing.JOptionPane;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import java.util.ArrayList;
import javax.swing.text.Utilities;

public class Venda extends javax.swing.JFrame {

    /**
     * Creates new form Venda
     */
    public Venda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtIDPro = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        lblIDPro = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaProduto = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        txtProduto = new javax.swing.JTextField();
        txtValorTotal = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtQuantidade = new javax.swing.JTextField();
        txtValorV = new javax.swing.JTextField();
        btnAdicionar = new javax.swing.JButton();
        btRegistrarVenda = new javax.swing.JButton();
        jpCabecalho = new javax.swing.JPanel();
        lbSairVenda = new javax.swing.JLabel();
        lbCabecalho = new javax.swing.JLabel();
        lbVendaLogo = new javax.swing.JLabel();
        jpSubtotal = new javax.swing.JPanel();
        txtSubtotal = new javax.swing.JTextField();
        lbSubtotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtIDPro.setBackground(new java.awt.Color(204, 204, 204));
        txtIDPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDProActionPerformed(evt);
            }
        });
        getContentPane().add(txtIDPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 70, -1));

        btnConsultar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btnConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/pesquisar-24.png"))); // NOI18N
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });
        getContentPane().add(btnConsultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 30, 20));

        lblIDPro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblIDPro.setText("Código");
        getContentPane().add(lblIDPro, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 50, 20));

        TabelaProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Produto", "Quantidade", "Valor Unitario", "ValorTotal R$"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TabelaProduto);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, -1, 200));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Produto");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 60, 20));

        txtProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtProdutoActionPerformed(evt);
            }
        });
        getContentPane().add(txtProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 130, -1));

        txtValorTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorTotalActionPerformed(evt);
            }
        });
        getContentPane().add(txtValorTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 50, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Quantidade");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Valor Total");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 130, 100, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Valor Unitario");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 100, 20));

        txtQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQuantidadeFocusLost(evt);
            }
        });
        txtQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantidadeActionPerformed(evt);
            }
        });
        getContentPane().add(txtQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 50, -1));

        txtValorV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtValorVActionPerformed(evt);
            }
        });
        getContentPane().add(txtValorV, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 50, -1));

        btnAdicionar.setBackground(new java.awt.Color(0, 153, 0));
        btnAdicionar.setText("Adicionar");
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, 90, 40));

        btRegistrarVenda.setBackground(new java.awt.Color(0, 102, 51));
        btRegistrarVenda.setForeground(new java.awt.Color(255, 255, 255));
        btRegistrarVenda.setText("Registrar Venda");
        btRegistrarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRegistrarVendaActionPerformed(evt);
            }
        });
        getContentPane().add(btRegistrarVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 130, 120, 40));

        jpCabecalho.setBackground(new java.awt.Color(17, 128, 216));
        jpCabecalho.setForeground(new java.awt.Color(255, 255, 255));
        jpCabecalho.setMaximumSize(new java.awt.Dimension(853, 29));
        jpCabecalho.setMinimumSize(new java.awt.Dimension(853, 29));

        lbSairVenda.setForeground(new java.awt.Color(255, 255, 255));
        lbSairVenda.setText("Sair");
        lbSairVenda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbSairVendaMouseClicked(evt);
            }
        });

        lbCabecalho.setBackground(new java.awt.Color(17, 128, 216));
        lbCabecalho.setForeground(new java.awt.Color(255, 255, 255));
        lbCabecalho.setText("Venda");
        lbCabecalho.setMaximumSize(new java.awt.Dimension(853, 29));
        lbCabecalho.setMinimumSize(new java.awt.Dimension(853, 29));
        lbCabecalho.setPreferredSize(new java.awt.Dimension(853, 29));

        lbVendaLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagem/venda.png"))); // NOI18N

        javax.swing.GroupLayout jpCabecalhoLayout = new javax.swing.GroupLayout(jpCabecalho);
        jpCabecalho.setLayout(jpCabecalhoLayout);
        jpCabecalhoLayout.setHorizontalGroup(
            jpCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCabecalhoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbVendaLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(lbSairVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(403, Short.MAX_VALUE))
        );
        jpCabecalhoLayout.setVerticalGroup(
            jpCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCabecalhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lbCabecalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(lbSairVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(lbVendaLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        getContentPane().add(jpCabecalho, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        jpSubtotal.setBackground(new java.awt.Color(153, 153, 153));

        txtSubtotal.setEditable(false);
        txtSubtotal.setBackground(new java.awt.Color(153, 153, 153));
        txtSubtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSubtotal.setText("0");
        txtSubtotal.setBorder(null);

        lbSubtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSubtotal.setText("SUBTOTAL DA COMPRA");

        javax.swing.GroupLayout jpSubtotalLayout = new javax.swing.GroupLayout(jpSubtotal);
        jpSubtotal.setLayout(jpSubtotalLayout);
        jpSubtotalLayout.setHorizontalGroup(
            jpSubtotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 460, Short.MAX_VALUE)
            .addGroup(jpSubtotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpSubtotalLayout.createSequentialGroup()
                    .addContainerGap(328, Short.MAX_VALUE)
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
            .addGroup(jpSubtotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpSubtotalLayout.createSequentialGroup()
                    .addComponent(lbSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 136, Short.MAX_VALUE)))
        );
        jpSubtotalLayout.setVerticalGroup(
            jpSubtotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
            .addGroup(jpSubtotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpSubtotalLayout.createSequentialGroup()
                    .addComponent(txtSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(jpSubtotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jpSubtotalLayout.createSequentialGroup()
                    .addComponent(lbSubtotal, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        getContentPane().add(jpSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 379, 460, 60));

        setSize(new java.awt.Dimension(467, 466));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
private Produto produto;
    private DefaultTableModel Tabela;


    private void txtIDProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDProActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDProActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed

        try {
            // Conectar com o BD
            Connection con;
            PreparedStatement st;
            ResultSet rs;

            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/lojinha", "root", "46813252");

            st = con.prepareStatement("SELECT *FROM  produto WHERE IDPro = ?");
            st.setString(1, txtIDPro.getText());
            rs = st.executeQuery();
            if (rs.next()) { // se encontrou ID no BD
                txtProduto.setText(rs.getString("Produto"));
                txtValorV.setText(rs.getString("ValorV"));

            } else {
                JOptionPane.showMessageDialog(null, "Produto não encontrado");
            }
        } catch (ClassNotFoundException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro no acesso à base de dados. Entre em contato com o administrador e informe o erro: " + ex.getMessage());
        }


    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtProdutoActionPerformed

    private void txtValorTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorTotalActionPerformed

    private void txtQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantidadeActionPerformed
        Somatotal();


    }//GEN-LAST:event_txtQuantidadeActionPerformed

    private void txtValorVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtValorVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtValorVActionPerformed


    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed

        //Obtém a tabela para trabalhar nela
        Tabela = (DefaultTableModel) TabelaProduto.getModel();

        if (!txtIDPro.getText().equalsIgnoreCase("Clique aqui para pesquisar o produto...")) {

            //Cria array com valores do produto
            Object[] Novo = new Object[5];
            //Cada dado na coluna correspondente
            Novo[0] = txtIDPro.getText();
            Novo[1] = txtProduto.getText();
            Novo[2] = txtQuantidade.getText();
            Novo[3] = txtValorV.getText();
            Novo[4] = Float.parseFloat(txtValorTotal.getText());

//Adiciona a linha de dados na tabela
            Tabela.addRow(Novo);
            atualizaSubtotal();
            limpaVenda();

        } else {
            //informa usuario que nao tem quantidade suficiente em estoque 
            //para inserir na venda
            JOptionPane.showMessageDialog(rootPane,
                    "Erro, Acionar o Administrador do sistema! \n");


    }//GEN-LAST:event_btnAdicionarActionPerformed

    }

    private void btRegistrarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRegistrarVendaActionPerformed
        VendaDao Vendido = new VendaDao();
        Tabela tabela = new DTO.Tabela();

        Tabela = (DefaultTableModel) TabelaProduto.getModel();

        for (int i = 0; i + 1 <= TabelaProduto.getModel().getRowCount(); i++) {
            //obtem o id dessa linha
          
            tabela.setCodigo((String) TabelaProduto.getValueAt(i, 0));
            tabela.setProduto((String) TabelaProduto.getValueAt(i, 1));
            tabela.setQuantidade((Double) TabelaProduto.getValueAt(i, 2));
            tabela.setValorUnitario((Double) TabelaProduto.getValueAt(i, 3));
            tabela.setValorTotal((Float) TabelaProduto.getValueAt(i, 4));
            
            Object[] Novo = new Object[5];

            Vendido.registrar(tabela);

            int result = Vendido.registrar(tabela);

            if (result == 1) { // se conectou {

                JOptionPane.showMessageDialog(null, "Usuario cadastrado com sucesso.");

            } else {
                JOptionPane.showMessageDialog(null, "Ocorreu um erro ao cadastrar usuário");

            }
        }
    }//GEN-LAST:event_btRegistrarVendaActionPerformed

    private void lbSairVendaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbSairVendaMouseClicked
        this.dispose();
        //this.doDefaultCloseAction();

        //realiza a limpeza dos campos para nova venda quando abrir
        limpaVenda();
    }//GEN-LAST:event_lbSairVendaMouseClicked

    private void txtQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQuantidadeFocusLost
        Somatotal();
    }//GEN-LAST:event_txtQuantidadeFocusLost

    public void atualizaSubtotal() {
        Float subtotal = 0f;
        int valor = TabelaProduto.getRowCount();

        //faz cálculo de subtotal da compra
        for (int i = 0; i < valor; i++) {

            subtotal += (Float) TabelaProduto.getValueAt(i, 4);
        }

        //insere valor subtotal da compra na label
        txtSubtotal.setText(subtotal.toString());

    }

    public void limpaVenda() {
        //Limpa todos os campos de produto
        txtIDPro.setText("");
        txtProduto.setText("Clique aqui para pesquisar o produto...");
        txtQuantidade.setText("");
        txtValorTotal.setText("0");
        txtValorV.setText("0");
    }

    private void Somatotal() {
        double quantidade, valorV, soma;
        quantidade = Double.parseDouble(txtQuantidade.getText());
        valorV = Double.parseDouble(txtValorV.getText());
        soma = quantidade * valorV;

        txtValorTotal.setText(String.valueOf(soma));

    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entrada.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Venda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelaProduto;
    private javax.swing.JButton btRegistrarVenda;
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpCabecalho;
    private javax.swing.JPanel jpSubtotal;
    private javax.swing.JLabel lbCabecalho;
    private javax.swing.JLabel lbSairVenda;
    private javax.swing.JLabel lbSubtotal;
    private javax.swing.JLabel lbVendaLogo;
    private javax.swing.JLabel lblIDPro;
    private javax.swing.JTextField txtIDPro;
    private javax.swing.JTextField txtProduto;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtSubtotal;
    private javax.swing.JTextField txtValorTotal;
    private javax.swing.JTextField txtValorV;
    // End of variables declaration//GEN-END:variables
}
